name: deployment-status

image:
  repository: quay.io/reevoo/deployment-status

env:
  DATABASE_URL:
    doc: postgresql url
    secret: true
  PORT:
    doc: Puma port
    value: 5000
  WEB_CONCURRENCY:
    doc: Number of Puma workers
    value: 2
  WEB_MIN_THREADS:
    doc: Number of Puma threads
    value: 2
  WEB_MAX_THREADS:
    doc: Number of Puma threads
    value: 5

hooks:
  migrate:
    command: ["bin/migrate"]
    hook: pre-install,pre-upgrade
    weight: 1

app:
  replicas: 1
  command: ["bin/server"]
  port: 5000
  livenessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: http
  readinessProbe:
    initialDelaySeconds: 30
    httpGet:
      path: /healthcheck
      port: http
  resources:
    requests:
      memory: 150Mi
      cpu: 10m
    limits:
      memory: 300Mi
      cpu: 100m

ingress:
  access: internal
